server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
